from __future__ import annotations

import ctypes
import threading
import time
from ctypes import wintypes


WH_MOUSE_LL = 14
WM_LBUTTONDOWN = 0x0201
WM_LBUTTONUP = 0x0202
LLMHF_INJECTED = 0x00000001


class POINT(ctypes.Structure):
    _fields_ = [("x", wintypes.LONG), ("y", wintypes.LONG)]


class MSLLHOOKSTRUCT(ctypes.Structure):
    _fields_ = [
        ("pt", POINT),
        ("mouseData", wintypes.DWORD),
        ("flags", wintypes.DWORD),
        ("time", wintypes.DWORD),
        ("dwExtraInfo", ctypes.POINTER(wintypes.ULONG)),
    ]


class MSG(ctypes.Structure):
    _fields_ = [
        ("hwnd", wintypes.HWND),
        ("message", wintypes.UINT),
        ("wParam", wintypes.WPARAM),
        ("lParam", wintypes.LPARAM),
        ("time", wintypes.DWORD),
        ("pt", POINT),
    ]


LowLevelMouseProc = ctypes.WINFUNCTYPE(wintypes.LPARAM, ctypes.c_int, wintypes.WPARAM, wintypes.LPARAM)


class Hotkeys:
    def __init__(self) -> None:
        self.user32 = ctypes.windll.user32
        self.kernel32 = ctypes.windll.kernel32
        self._edge_prev: dict[int, bool] = {}
        self._physical_left_down = False
        self._physical_left_down_at = 0.0
        self._mouse_hook_ready = False
        self._mouse_hook = None
        self._mouse_proc = None
        self._mouse_thread = threading.Thread(target=self._mouse_hook_thread, daemon=True, name="physical-mouse-hook")
        self._mouse_thread.start()

    def _state(self, virtual_key: int) -> int:
        return int(self.user32.GetAsyncKeyState(int(virtual_key)))

    def is_down(self, virtual_key: int) -> bool:
        return bool(self._state(virtual_key) & 0x8000)

    def is_physical_left_down(self) -> bool | None:
        """Physical left button state, ignoring our own SendInput injected events.

        Returns None if the low-level mouse hook failed to initialize.
        """
        if not self._mouse_hook_ready:
            return None
        return self._physical_left_down

    def physical_left_down_at(self) -> float | None:
        if not self._mouse_hook_ready:
            return None
        return self._physical_left_down_at

    def was_pressed(self, virtual_key: int) -> bool:
        """Return True once for a key press, even if the tap is very short."""
        vk = int(virtual_key)
        state = self._state(vk)
        down = bool(state & 0x8000)
        latched = bool(state & 0x0001)
        edge = down and not self._edge_prev.get(vk, False)
        self._edge_prev[vk] = down
        return latched or edge

    def _mouse_hook_thread(self) -> None:
        try:
            self.user32.SetWindowsHookExW.argtypes = [ctypes.c_int, LowLevelMouseProc, wintypes.HINSTANCE, wintypes.DWORD]
            self.user32.SetWindowsHookExW.restype = wintypes.HHOOK
            self.user32.CallNextHookEx.argtypes = [wintypes.HHOOK, ctypes.c_int, wintypes.WPARAM, wintypes.LPARAM]
            self.user32.CallNextHookEx.restype = wintypes.LPARAM
            self.user32.GetMessageW.argtypes = [ctypes.POINTER(MSG), wintypes.HWND, wintypes.UINT, wintypes.UINT]
            self.user32.GetMessageW.restype = wintypes.BOOL

            def proc(n_code: int, w_param: int, l_param: int) -> int:
                if n_code >= 0 and l_param:
                    info = ctypes.cast(l_param, ctypes.POINTER(MSLLHOOKSTRUCT)).contents
                    # Ignore injected events generated by this program/backends.
                    if not (int(info.flags) & LLMHF_INJECTED):
                        if int(w_param) == WM_LBUTTONDOWN:
                            self._physical_left_down = True
                            self._physical_left_down_at = time.perf_counter()
                        elif int(w_param) == WM_LBUTTONUP:
                            self._physical_left_down = False
                return self.user32.CallNextHookEx(self._mouse_hook, n_code, w_param, l_param)

            self._mouse_proc = LowLevelMouseProc(proc)
            h_instance = self.kernel32.GetModuleHandleW(None)
            self._mouse_hook = self.user32.SetWindowsHookExW(WH_MOUSE_LL, self._mouse_proc, h_instance, 0)
            if not self._mouse_hook:
                return
            self._mouse_hook_ready = True
            msg = MSG()
            while self.user32.GetMessageW(ctypes.byref(msg), None, 0, 0) != 0:
                pass
        except Exception:
            self._mouse_hook_ready = False
